---
baseloop_directory: /ocean/projects/bio210019p/stevesho/data/preprocess/raw_files/chromatin_loops/processed_loops

baseloops: peakachu_deepanchor

experiment_name: regulatoryonly_cpgislands_ctcfccre_superenhancers_tads_tss_combinedloops

interaction_types: null

nodes:
  - cpgislands
  - ctcfccre
  - superenhancers
  - tads
  - tss

working_directory: /ocean/projects/bio210019p/stevesho/data/preprocess/graph_processing

# Note: the following node types are always defaulted: dyadic, enhancers, gencode, promoters