---
dirs:
  circuit_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/FANTOM5_individual_networks/394_individual_networks
  data_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/raw_files/hippocampus
  root_dir: /ocean/projects/bio210019p/stevesho/data/preprocess

interaction:
  circuits: hippocampus_adult.txt
  gct: GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct
  gencode: gencode_v26_genes_only_with_GTEx_targets.bed
  id_lookup: gencode_to_genesymbol_lookup_table.txt
  mirdip: brain_mirdip
  mirnatargets: mirtargets_filtered.txt
  ppis: IID_annotated_PPI.txt
  tf_marker: tf_marker.txt

options:
  cpg_filetype: GEO
  cpg_liftover: true

resources:
  chromfile: /ocean/projects/bio210019p/stevesho/resources/hg38.chrom.sizes.txt
  fasta: /ocean/projects/bio210019p/stevesho/resources/hg38.fa
  key_protein_abundance: brain_cortex
  key_tpm: brain_hippocampus
  liftover: /ocean/projects/bio210019p/stevesho/resources/liftOver
  liftover_chain: /ocean/projects/bio210019p/stevesho/resources/hg19ToHg38.over.chain.gz
  marker_name: Brain
  ppi_tissue: hippocampal formation
  tf_motifs: /ocean/projects/bio210019p/stevesho/resources/collapsed_motifs_overlapping_consensus_footprints_hg38.bed
  tissue: hippocampus
  tissue_name: Brain - Hippocampus
  tpm: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/tpm/brain_hippocampus.tpm.txt

local:
  cnv: cnv_hg38.bed
  cpgislands: cpgislands_hg38_parsed.bed
  ctcfccre: ctcfccre_parsed_hg38.bed
  dyadic: dyadic_epimap_screen_overlap.bed
  enhancers: enhancers_epimap_screen_overlap.bed
  gencode: gencode_v26_genes_only_with_GTEx_targets.bed
  gencode_attr: gencode_v26_node_attr.bed
  indels: indels_hg38.bed
  line: line_hg38.bed
  ltr: ltr_hg38.bed
  microsatellites: microsatellites_hg38_parsed.bed
  phastcons: phastcons_gt_0.9_h38.bed
  polyasites: polyasites_filtered_hg38.bed
  promoters: promoters_epimap_screen_overlap.bed
  rbpbindingistes: rbpbindingsites_parsed_hg38.bed
  recombination: recombination_hg38.bed
  repg1b: repg1b_hg38.bed
  repg2: repg2_hg38.bed
  reps1: reps1_hg38.bed
  reps2: reps2_hg38.bed
  reps3: reps3_hg38.bed
  reps4: reps4_hg38.bed
  rnarepeat: rnarepeat_hg38.bed
  simplerepeats: simplerepeats_hg38.bed
  sine: sine_hg38.bed
  snp: snp_hg38.bed
  tss: tss_parsed_hg38.bed

tissue_specific:
  ATAC: ATAC-seq_narrow_5_merged.bed
  CTCF: CTCF_narrow_5_merged.bed
  DNase: DNase-seq_narrow_5_merged.bed
  H3K27ac: H3K27ac_narrow_5_merged.bed
  H3K27me3: H3K27me3_narrow_5_merged.bed
  H3K36me3: H3K36me3_narrow_5_merged.bed
  H3K4me1: H3K4me1_narrow_5_merged.bed
  H3K4me2: H3K4me2_narrow_5_merged.bed
  H3K4me3: H3K4me3_narrow_5_merged.bed
  H3K79me2: H3K79me2_narrow_5_merged.bed
  H3K9ac: H3K9ac_narrow_5_merged.bed
  H3K9me3: H3K9me3_narrow_4_merged.bed
  POLR2A: POLR2A_narrow_5_merged.bed
  RAD21: RAD21_narrow_5_merged.bed
  SMC3: SMC3_narrow_5_merged.bed
  chromatinloops: Hippocampus.hg38.combined_loops
  cpg: CpgMethly_hippocampus_GSE46644.bed
  crms: consensuses.bed
  super_enhancer: SE_02_0351_SE_hg38.bedipp
  tads: Hippocampus_Schmitt2016-raw_TADs.txt
  tf_binding: interval.all.fps.0.0001.bed