resources:
  tissue: 'hippocampus'
  tissue_name: 'Brain - Hippocampus'
  locop_tissue: 'Brain_Hippocampus'
  chromfile: '/ocean/projects/bio210019p/stevesho/resources/hg38.chrom.sizes.txt'
  fasta: '/ocean/projects/bio210019p/stevesho/resources/hg38.fa'

dirs:
  data_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess/raw_files/hippocampus'  # place where unprocessed files exists
  root_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess'  # place to process data
  shared_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess/shared_data'
  ppi_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/Humanproteinatlas-Protein'
  poly_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/PDUI_polyA_sites'

tissue_specific:
  cpg: 'CpgMethly_hippocampus_GSE46644.bed' ### downloaded from GEO GSE46644
  dnase: 'ENCFF102QMS.bed'
  H3K27ac: 'H3K27ac_hippocampus_ENCFF551LSF.bed'
  H3K27me3: 'H3K27me3_hippocampus_ENCFF810LJW.bed'
  H3K36me3: 'H3K36me3_hippocampus_ENCFF442BXP.bed'
  H3K4me1: 'H3K4me1_hippocampus_ENCFF328YWW.bed'
  H3K4me3: 'H3K4me3_hippocampus_ENCFF451IGE.bed'
  H3K9ac: 'H3K9ac_astrocyte_ENCFF649IVK.bed'
  H3K9me3: 'H3K9me3_hippocampus_ENCFF265CFH.bed'
  chromhmm: 'E071_18_core_K27ac_hg38lift_mnemonics.bed'
  chromatinloops: 'Schmitt_2016.Hippocampus.hg38.peakachu-merged.loops'
  enhancers_e_e: 'HMEC_EP.txt'
  enhancers_e_g: ''
  tf_binding: ''
  tads: 'Hippocampus_Schmitt2016-raw_TADs.txt'
  ctcf: 'ENCFF450EVR.bed'
  polr2a: ''

shared:
  cpgislands: 'cpgislands_hg38_parsed.bed'
  gencode: 'gencode_v26_genes_only_with_GTEx_targets.bed'
  regions: 'gene_regions_250000.bed'
  microsatellites: 'microsatellites_hg38_parsed.bed'
  phastcons: 'phastcons_gt_0.9_h38.bed'
  repeatmasker: 'repeatmasker_hg38_parsed.bed'
  simplerepeats: 'simplerepeats_hg38.bed'

interaction:
    id_lookup: 'gencode_to_genesymbol_lookup_table.txt'
    gct: 'GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct'
    gencode: 'gencode_v26_genes_only_with_GTEx_targets.bed'
    circuits: 'hippocampus_adult.txt'
    cops: 'all_cops_gtex.tsv'
    shared_eqtls: 'shared_eqtls_gtex.tsv'
    polyadenylation: 'Brain_Hippocampus.txt'
    ppis: 'brain_hippocampus.tsv'

options:
  cpg_liftover: True
  cpg_filetype: 'GEO' #ENCODE or GEO

### Note: if we have to remove something.. remove H3K9ac
