---
dirs:
  circuit_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/FANTOM5_individual_networks/394_individual_networks
  data_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/raw_files/liver
  root_dir: /ocean/projects/bio210019p/stevesho/data/preprocess
  shared_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data
interaction:
  circuits: liver_adult.txt
  entrez_file: entrez_to_genesymbol.txt
  gct: GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct
  gencode: gencode_v26_genes_only_with_GTEx_targets.bed
  id_lookup: gencode_to_genesymbol_lookup_table.txt
  mirdip: liver_mirdip
  mirnatargets: mirtargets_filtered.txt
  ppis: IID_annotated_PPI.txt
  tf_marker: tf_marker.txt
options:
  cpg_filetype: ENCODE
  cpg_liftover: false
resources:
  chromfile: /ocean/projects/bio210019p/stevesho/resources/hg38.chrom.sizes.txt
  fasta: /ocean/projects/bio210019p/stevesho/resources/hg38.fa
  liftover: /ocean/projects/bio210019p/stevesho/resources/liftOver
  liftover_chain: /ocean/projects/bio210019p/stevesho/resources/hg19ToHg38.over.chain.gz
  marker_name: Liver
  ppi_tissue: liver
  tissue: liver
  tissue_name: Liver
  tpm: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/tpm/liver.tpm.txt
  window: 125000
shared:
  ctcfccre: ctcfccre_parsed_hg38.bed
  cnv: cnv_hg38.bed
  cpgislands: cpgislands_hg38_parsed.bed
  gencode: gencode_v26_genes_only_with_GTEx_targets.bed
  gencode_attr: gencode_v26_node_attr.bed
  indels: indels_hg38.bed
  line: line_hg38.bed
  ltr: ltr_hg38.bed
  microsatellites: microsatellites_hg38_parsed.bed
  mirnatargets: mirnatargets_parsed_hg38.bed
  phastcons: phastcons_gt_0.9_h38.bed
  polyasites: polyasites_filtered_hg38.bed
  promoters: promoters_parsed_hg38.bed
  rbpbindingistes: rbpbindingsites_parsed_hg38.bed
  recombination: recombination_hg38.bed
  repg1b: repg1b_hg38.bed
  repg2: repg2_hg38.bed
  reps1: reps1_hg38.bed
  reps2: reps2_hg38.bed
  reps3: reps3_hg38.bed
  reps4: reps4_hg38.bed
  rnarepeat: rnarepeat_hg38.bed
  simplerepeats: simplerepeats_hg38.bed
  sine: sine_hg38.bed
  snp: snp_hg38.bed
  tss: tss_parsed_hg38.bed
tissue_specific:
  H3K27ac: H3K27ac_liver_ENCFF382EMP.bed
  H3K27me3: H3K27me3_liver_ENCFF210DQA.bed
  H3K36me3: H3K36me3_liver_ENCFF808ULR.bed
  H3K4me1: H3K4me1_liver_ENCFF003KVZ.bed
  H3K4me3: H3K4me3_liver_ENCFF522CRH.bed
  H3K9me3: H3K9me3_liver_ENCFF789WSF.bed
  chromatinloops: Leung_2015.Liver.hg38.peakachu-merged.loops
  cpg: cpg_methyl_ENCFF080ETP.bed
  ctcf: ENCFF046XEZ.bed
  dnase: ENCFF905THS.bed
  enhancers_e_e: Enhancer_Enhancer_network_082619.txt
  enhancers_e_g: Enhancer_gene_network_082619.txt
  polr2a: ENCFF064ASM.bed
  polyadenylation: Liver.txt
  super_enhancer: SE_02_1299_SE_hg38.bed
  tads: Liver_STL011_Leung_2015-raw_TADs.txt
  tf_binding: liver_hint_20-footprint.bed  # mirnatargets: 'mirtargets_filtered.txt'
