---
dirs:
  circuit_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/FANTOM5_individual_networks/394_individual_networks
  data_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/raw_files/mammary
  poly_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/PDUI_polyA_sites
  root_dir: /ocean/projects/bio210019p/stevesho/data/preprocess
  shared_dir: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data
interaction:
  circuits: breast_adult.txt
  entrez_file: entrez_to_genesymbol.txt
  gct: GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct
  gencode: gencode_v26_genes_only_with_GTEx_targets.bed
  id_lookup: gencode_to_genesymbol_lookup_table.txt
  mirdip: breast_mirdip
  mirnatargets: mirtargets_filtered.txt
  ppis: IID_annotated_PPI.txt
  tf_marker: tf_marker.txt
options:
  cpg_filetype: ENCODE
  cpg_liftover: false
resources:
  chromfile: /ocean/projects/bio210019p/stevesho/resources/hg38.chrom.sizes.txt
  fasta: /ocean/projects/bio210019p/stevesho/resources/hg38.fa
  marker_name: Breast
  ppi_tissue: mammary gland
  tissue: mammary
  tissue_name: Breast - Mammary Tissue
  tpm: /ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/tpm/breast_mammary_tissue.tpm.txt
  window: 125000
shared:
  cpgislands: cpgislands_hg38_parsed.bed
  gencode: gencode_v26_genes_only_with_GTEx_targets.bed
  line: line_hg38.bed
  ltr: ltr_hg38.bed
  microsatellites: microsatellites_hg38_parsed.bed
  mirnatargets: mirnatargets_parsed_hg38.bed
  phastcons: phastcons_gt_0.9_h38.bed
  polyasites: polyasites_filtered_hg38.bed
  promoters: promoters_parsed_hg38.bed
  rbpbindingistes: rbpbindingsites_parsed_hg38.bed
  rnarepeat: rnarepeat_hg38.bed
  simplerepeats: simplerepeats_hg38.bed
  sine: sine_hg38.bed
  tss: tss_parsed_hg38.bed
tissue_specific:
  H3K27ac: H3K27ac_breast_ENCFF929WUQ.bed
  H3K27me3: H3K27me3_breast_ENCFF518UWB.bed
  H3K36me3: H3K36me3_breast_ENCFF745BUS.bed
  H3K4me1: H3K4me1_breast_ENCFF401CLZ.bed
  H3K4me3: H3K4me3_breast_ENCFF497MQY.bed
  H3K9me3: H3K9me3_breast_ENCFF444VMM.bed
  chromatinloops: Rao_2014.HMEC.hg38.peakachu-merged.loops
  cpg: ENCFF478RLX.bed
  ctcf: ENCFF530ARF.bed
  dnase: ENCFF628QME.bed
  enhancers_e_e: Enhancer_Enhancer_network_082619.txt
  enhancers_e_g: Enhancer_gene_network_082619.txt
  polr2a: ENCFF555UBC.bed
  polyadenylation: Breast_Mammary_Tissue.txt
  super_enhancer: SE_01_0045_SE_hg38.bed
  tads: HMEC_Rao_2014-raw_TADs.txt
  tf_binding: mammary_gland_hint_20-footprint.bed