data_dir: ''  # place where unprocessed files exists
root_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess'  # place to process data
ppi_dit: '/ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/Humanproteinatlas-Protein'
poly_dir: '/ocean/projects/bio210019p/stevesho/data/preprocess/shared_data/interaction/PDUI_polyA_sites'
tissue: ''

tissue_specific:
  cpg: '' ### downloaded from GEO GSE46644
  dnase: ''
  H3K27ac: ''
  H3K27me3: ''
  H3K36me3: ''
  H3K4me1: ''
  H3K4me3: ''
  H3K9ac: ''
  H3K9me3: ''
  chromHMM: ''
  chromatinloops: ''
  regulatorybuild: ''
  enhancers: ''
  tads: ''
  ctcf: ''
  polr2a: ''

shared:
  cpgislands: 'cpgislands_hg38_parsed.bed'
  gencode: 'gencode_v26_genes_only_with_GTEx_targets.bed'
  regions: 'gene_regions_250000.bed'
  microsatellites: 'microsatellites_hg38_parsed.bed'
  phastcons: 'phastcons_gt_0.9_h38.bed'
  repeatmasker: 'repeatmasker_hg38_parsed.bed'
  sumplerepeats: 'simplerepeats_hg38.bed'

options:
  cpg_liftover: False
  cpg_filetype: '' #ENCODE or GEO

### Note: if we have to remove something.. remove H3K9ac
