train:
  split: "scaffold"
  shuffle_raw_train_data: True

validation:
  split: "scaffold"
  shuffle_raw_train_data: False # avoid any shuffling in val data

test:
  split: "scaffold"
  shuffle_raw_train_data: False # avoid any shuffling in test data
