train:
  split: "scaffold"
  shuffle_raw_train_data: True
  mode: 'train'

validation:
  split: "scaffold"
  shuffle_raw_train_data: False # avoid any shuffling in val data
  mode: 'validation'

test:
  split: "scaffold"
  shuffle_raw_train_data: False # avoid any shuffling in test data
  mode: 'test'
